# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 09:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/2icon3.png', upload_to='img', verbose_name='人员头像')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('birthday', models.CharField(max_length=20, verbose_name='生日')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('home', models.CharField(max_length=100, verbose_name='家乡')),
                ('phonenum', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户基本信息表',
                'verbose_name_plural': '用户基本信息表',
                'db_table': 'information',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d+', '号码必须为数字')], verbose_name='用户手机号')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='密码')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now_add=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户注册表',
                'verbose_name_plural': '用户注册表',
                'db_table': 'users',
            },
        ),
    ]
