# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 10:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^\\d+', '号码必须为数字')], verbose_name='用户手机号'),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='密码'),
        ),
    ]
